//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AStudio.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ASTUDIO_DIALOG              102
#define IDD_TARGET                      102
#define IDD_PATHS                       106
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDB_LOGO                        130
#define IDR_ACCELERATOR1                131
#define IDD_BODY                        132
#define IDD_MATERIALS                   133
#define IDD_MOTIONS                     134
#define IDD_TEXTINPUT                   135
#define IDD_SETTINGS                    136
#define IDD_MESSAGES                    137
#define IDD_LOGOPAGE                    137
#define IDD_NEWPROJECT                  138
#define IDC_EDITBODY                    1000
#define IDC_BROWSE                      1001
#define IDC_BROWSEBODY                  1001
#define IDC_MATERIALSLIST               1002
#define IDC_EDITTEXTURE                 1003
#define IDC_BROWSETEXTURE               1004
#define IDC_CHECKCOLOR                  1005
#define IDC_EDITRED                     1006
#define IDC_EDITGREEN                   1007
#define IDC_EDITBLUE                    1008
#define IDC_MATERIALDEFAULT             1009
#define IDC_MOTIONSLIST                 1010
#define IDC_CHOOSECOLOR                 1010
#define IDC_EDITMOTION                  1011
#define IDC_EDITBODYPATH                1011
#define IDC_BROWSEMOTION                1012
#define IDC_FORCERELATIVE               1012
#define IDC_EDITTEXTURE2                1013
#define IDC_ADDMATERIAL                 1013
#define IDC_BROWSEVIEWER                1013
#define IDC_EDITOPTIMIZE                1013
#define IDC_MOTIONDEFAULT               1014
#define IDC_EDITMATERIALSPATH           1014
#define IDC_BROWSE3DSMAX                1014
#define IDC_ADDMOTION                   1015
#define IDC_EDITMOTIONSPATH             1015
#define IDC_EDITOPTLEVEL                1015
#define IDC_DELETEMOTION                1016
#define IDC_EDITVIEWERPATH              1016
#define IDC_EDITTEMPFILESDIR            1016
#define IDC_SPINOPTIMIZE                1017
#define IDC_COMBOBONE                   1018
#define IDC_EDITTARGET                  1019
#define IDC_BROWSETARGET                1020
#define IDC_FORMATBINARY                1021
#define IDC_FORMATTEXT                  1022
#define IDC_MATERIALSFROMBODY           1022
#define IDC_MOTIONSFROMBODY             1024
#define IDC_RESETPAGE                   1025
#define IDC_BODYMAX                     1026
#define IDS_COMPILEFAILED               1026
#define IDC_BODYNFO                     1027
#define IDS_COMPILESUCCESS              1027
#define IDC_BODYBDY                     1028
#define IDS_NEWFILEPROMPT               1028
#define IDC_BODYACT                     1029
#define IDC_EDIT1                       1030
#define IDC_MOTIONMAX                   1031
#define IDC_MOTIONKEY                   1032
#define IDC_MOTIONMOT                   1033
#define IDC_MOTIONACT                   1034
#define IDC_EDIT3DSMAXPATH              1035
#define IDC_MESSAGES                    1036
#define IDC_OPTIMIZE                    1039
#define IDC_BROWSEPROJECT               1040
#define IDC_USEPROJECTDIR               1041
#define IDC_EDITPROJECTNAME             1042
#define IDC_EDITBONE                    1043
#define IDC_RENAMEMOTION                1044
#define IDC_RENAMEMATERIAL              1045
#define IDC_DELETEMATERIAL              1046
#define IDC_OPTCHECK                    1049
#define IDC_SPINOPTLEVEL                1050
#define ID_FILEOPEN                     32771
#define ID_FILECLOSE                    32772
#define IDS_UNTITLED                    32773
#define ID_FILEEXIT                     32774
#define ID_FILENEW                      32775
#define ID_HELPABOUT                    32776
#define ID_FILESAVE                     32777
#define ID_FILESAVEAS                   32778
#define ID_BUILDBUILD                   32779
#define ID_BUILDALL                     32780
#define IDS_MODIFIED                    32781
#define ID_BUILDCLEAN                   32782
#define ID_BUILDSETTINGS                32783
#define ID_PROJECTSETTINGS              32784
#define ID_PROJECTBUILD                 32785
#define ID_PROJECTBUILDALL              32786
#define ID_PROJECTCLEAN                 32787
#define ID_DUMMYESC                     32788
#define IDS_CAPTION                     32788
#define IDS_UNTITLEDFILE                32789
#define IDS_ACTFILEFILTER               32790
#define IDS_ACTFILEEXT                  32791
#define IDS_ACTFILEFILTERDESC           32792
#define IDS_BDYFILEFILTER               32793
#define IDS_BDYFILEEXT                  32794
#define IDS_BDYFILEFILTERDESC           32795
#define IDS_BMPFILEFILTER               32796
#define IDS_BMPFILEEXT                  32797
#define IDS_BMPFILEFILTERDESC           32798
#define IDS_MOTFILEFILTER               32799
#define IDS_MOTFILEEXT                  32800
#define IDS_MOTFILEFILTERDESC           32801
#define IDS_INIFILE_NAME                32802
#define IDS_WRITEERROR                  32803
#define IDS_ASPFILEFILTER               32804
#define IDS_ASPFILEEXT                  32805
#define IDS_READERROR                   32806
#define IDS_SAVEPROJECTPROMPT           32807
#define IDS_OPENPROJECTPROMPT           32808
#define IDS_TARGETPROMPT                32809
#define IDS_BODYPROMPT                  32810
#define IDS_TEXTUREPROMPT               32811
#define IDS_MATERIALPROMPT              32812
#define IDS_OUTOFMEMORY                 32813
#define IDS_3DSMAXPROMPT                32814
#define IDS_VIEWERPROMPT                32815
#define IDS_EXEFILEEXT                  32816
#define IDS_EXEFILEFILTER               32817
#define IDS_MOTIONFILEPROMPT            32818
#define IDS_MOTIONPROMPT                32819
#define IDS_ERRORADDMATERIAL            32820
#define IDS_ERRORADDMOTION              32821
#define IDS_ERRORDELMOTION              32822
#define IDS_MESSAGESHIDE                32823
#define IDS_MESSAGESSHOW                32824
#define IDS_CREATEERROR                 32825
#define IDS_PROJECTNAMEPROMPT           32826
#define IDS_OVERWRITEPROJECT            32827
#define IDS_PROJECTFILECREATEERROR      32828
#define IDS_BUILD                       32829
#define IDS_OPTIONSERR                  32830
#define IDS_RELATIVEPATH                32831
#define IDS_CANTSTARTCOMPILE            32832
#define IDS_STOPBUILD                   32833
#define IDS_BUILDING                    32834
#define IDS_CLEANING                    32835
#define IDS_CANCELREQUESTED             32836
#define IDS_NEWNAMEPROMPT               32837
#define IDS_MOTIONEXISTS                32838
#define IDS_CANTDROPMOTION              32839
#define IDS_ERRORDROPMOTION             32840
#define IDS_MATERIALEXISTS              32841
#define IDS_ERRORDELMATERIAL            32842
#define IDS_CANTDROPMATERIAL            32843
#define IDS_ERRORDROPMATERIAL           32844
#define ID_PROJECTACTORSUMMARY          32845
#define IDS_SUMMARYFAILED               32845

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32846
#define _APS_NEXT_CONTROL_VALUE         1051
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
