//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FUSION.rc
//
#define ID_DEFAULTS                     3
#define ID_DEFAULT                      3
#define IDC_BROWSE                      3
#define IDD_ABOUTBOX                    100
#define CG_ID_VIEW_DIALOGBAR            103
#define ID_TOOLBAR_COMBOBOX             104
#define IDC_ARROWENTITY                 104
#define ID_INDICATOR_SLOCK              106
#define ID_INDICATOR_SELINFO            107
#define ID_INDICATOR_WORLDPOS           108
#define ID_INDICATOR_CURSORINFO         109
#define ID_INDICATOR_GRID               110
#define ID_INDICATOR_SNAP               111
#define IDR_MAINFRAME                   128
#define IDR_THREDTYPE                   129
#define IDR_FUSIONTYPE                  129
#define IDR_BRUSHTOOLS                  130
#define IDS_LOAD_WARNING                130
#define IDS_NEWGROUP                    131
#define IDD_BRUSHDIALOG                 132
#define IDS_CREATEGROUPFAILED           132
#define IDD_CREATEBOX                   133
#define IDS_DEFAULTGROUPNAME            133
#define IDB_HOLLOWBOX                   134
#define IDS_NOBLANKMODEL                134
#define IDB_SOLIDBOX                    135
#define IDS_MODELEXISTS                 135
#define IDD_CREATE_SPHEROID             136
#define IDS_CAMERAENTITYNAME            136
#define IDB_SOLIDSPHERE                 137
#define IDS_MAPERROR                    137
#define IDB_HOLLOWSPHERE                138
#define IDD_CREATE_CYL                  139
#define IDB_CYLINDERBIT                 140
#define IDD_GRIDSETTINGSDIALOG          141
#define IDD_BSPMANAGERDIALOG            142
#define IDD_ENTITIES                    143
#define IDD_SELECTCLASSNAME             144
#define IDD_GROUPDIALOG                 145
#define IDD_STAIRCASEDIALOG             146
#define IDR_THRED_PALETTE1              147
#define IDD_GLOBALSETTINGS              148
#define IDD_FACEDIALOG                  149
#define IDD_TABDIALOG                   153
#define IDD_BRUSH_ENTITY_DIALOG         158
#define IDI_CUBE_PRIMITIVE              160
#define IDI_SPHEROID_PRIMITIVE          163
#define IDI_CYLINDER_PRIMITIVE          164
#define IDI_STAIRCASE_PRIMITIVE         165
#define IDI_LIGHT_ENTITY                167
#define IDI_PLAYERSTART_ENTITY          168
#define IDI_ACTOR_ENTITY                175
#define IDI_FLIPVERTICAL                176
#define IDI_FLIPHORIZONTAL              177
#define IDD_CREATE_ARCH                 178
#define IDI_ARCH_PRIMITIVE              179
#define IDD_PROGRESSDIALOG              180
#define IDD_CREATE_CONE                 181
#define IDI_CONE_PRIMITIVE              182
#define IDD_COMPILEDIALOG               183
#define IDC_PANCURSOR                   190
#define IDC_ARROWBRUSH                  191
#define IDC_POINTER                     191
#define IDD_CONSOLE                     191
#define IDD_OBJ_NAME_DLG                192
#define IDI_LIBOBJECT                   192
#define IDD_DIALOG1                     193
#define IDD_PROPEDIT                    194
#define IDD_KEYEDIT                     199
#define IDD_POINTKEYEDIT                204
#define IDD_STRUCTEDIT                  205
#define IDD_MODELEDIT                   206
#define IDD_MODELKEY                    207
#define IDI_PLAY                        208
#define IDI_RRSTART                     209
#define IDI_RRFRAME                     210
#define IDI_STOP                        211
#define IDI_FFFRAME                     212
#define IDI_FFEND                       213
#define IDD_ENTITYVISIBILITY            214
#define IDR_GROUPBAR                    219
#define ID_BRUSH_GROUPS_ADDTOGROUP      220
#define IDD_GROUPBAR                    221
#define IDD_PREFERENCES                 224
#define IDD_SKYDIALOG                   225
#define IDD_EVENTEDIT                   226
#define IDD_PATHSDIALOG                 227
#define IDD_PROJECTOPTIONS              228
#define IDC_EYEDROPPER                  229
#define IDD_LEVELOPTIONS                231
#define IDD_BOOLEDIT                    232
#define IDD_DIALOG2                     233
#define IDC_RESET_ALL                   1000
#define IDC_EDIT1                       1001
#define IDC_EDIT10                      1002
#define IDC_EDIT11                      1003
#define IDC_EDIT12                      1004
#define IDC_BOUNCELIMIT                 1006
#define IDC_FACELIGHTINTENSITY          1006
#define IDC_LIGHTSCALE                  1007
#define IDC_PATCHSIZE                   1008
#define IDC_REFLECTSCALE                1009
#define IDC_MINLIGHT                    1010
#define IDC_RESET_POSITION              1011
#define IDC_RESET_ROTATION              1012
#define IDC_RESET_SCALE                 1013
#define IDC_SOLID                       1014
#define IDC_XShear                      1014
#define IDC_HOLLOW                      1015
#define IDC_YSHEAR                      1015
#define IDC_XSIZE                       1016
#define IDC_ZSHEAR                      1016
#define IDC_RING                        1016
#define IDC_YSIZE                       1017
#define IDC_RESET_SHEAR                 1017
#define IDC_ZSIZE                       1018
#define IDC_THICKNESS                   1019
#define IDC_PICTURE                     1020
#define IDC_VERTSTRIPES                 1021
#define IDC_YSIZE2                      1021
#define IDC_HORSTRIPES                  1022
#define IDC_XSIZE2                      1022
#define IDC_RINGLENGTH                  1022
#define IDC_XSIZEBOT                    1023
#define IDC_ZSIZEBOT                    1024
#define IDC_TOPXSIZE                    1025
#define IDC_TOPXOFF                     1026
#define IDC_TOPZOFF                     1027
#define IDC_BOTXSIZE                    1028
#define IDC_BOTZSIZE                    1029
#define IDC_BOTXOFF                     1030
#define IDC_BOTZOFF                     1031
#define IDC_TOPZSIZE                    1032
#define IDC_GRIDSIZE                    1033
#define IDC_RebuildQuick                1035
#define IDC_REBUILDOPTIMAL              1036
#define IDC_ORIGINAL_POLYS              1037
#define IDC_SPLITS                      1038
#define IDC_TOTAL_POLYS                 1039
#define IDC_NODES                       1040
#define IDC_COPLANAR_NODES              1041
#define IDC_Defaults                    1043
#define IDC_PROGRESS1                   1046
#define IDC_PAIRS                       1047
#define IDC_PROPERTIESLIST              1047
#define IDC_SHOWLIGHTS                  1052
#define IDC_NEWKEYVALUE                 1054
#define IDC_KEY_EDIT                    1055
#define IDC_VALUE_EDIT                  1056
#define IDC_ENTITYLIST                  1057
#define IDC_ASSOCIATE_SELECTEDBRUSH     1058
#define IDC_ASSOCIATEGROUP              1059
#define IDC_NEWENTITY                   1060
#define IDC_NEWLIGHT                    1061
#define IDC_DELETEKEYVALUE              1062
#define IDC_DELETEENTITY                1063
#define IDC_LIST1                       1064
#define IDC_COLOURBUTTON                1065
#define IDC_CHECK1                      1066
#define IDC_BRUSHLIST                   1067
#define IDC_SKYRIGHT                    1067
#define IDC_VISDETAIL                   1067
#define IDC_NAME                        1068
#define IDC_CHECK3                      1068
#define IDC_SKYTOP                      1068
#define IDC_HULLSIZE                    1069
#define IDC_CHECK4                      1069
#define IDC_SKYBOTTOM                   1069
#define IDC_SKYFRONT                    1070
#define IDC_XSIZETOP                    1071
#define IDC_SKYBACK                     1071
#define IDC_ZSIZETOP                    1072
#define IDC_HEIGHT                      1073
#define IDC_WIDTH                       1074
#define IDC_LENGTH                      1075
#define IDC_NUMSLITS                    1075
#define IDC_NUMBEROFSTAIRS              1076
#define IDC_RADIUS                      1076
#define IDC_BUILDWATER                  1077
#define IDC_WALLSIZE                    1077
#define IDC_SIZE16                      1078
#define IDC_SIZE32                      1079
#define IDC_SIZE64                      1080
#define IDC_SIZE8                       1081
#define IDC_SHOWCOARSE                  1082
#define IDC_USEROTSNAP                  1083
#define IDC_SNAP15                      1084
#define IDC_SNAP30                      1085
#define IDC_SNAP45                      1086
#define IDC_SNAP60                      1087
#define IDC_SHOWFINE                    1088
#define IDC_SNAP90                      1088
#define IDC_ROTSNAPDEGREES              1089
#define IDC_BROWSEPAL                   1090
#define IDC_SIZE4                       1090
#define IDC_BROWSEWAD                   1091
#define IDC_PALETTEPATH                 1092
#define IDC_WADPATH                     1093
#define IDC_DISASSOCIATE                1094
#define IDC_AVENGERPATH                 1094
#define IDC_BROWSEAVENGER               1095
#define IDC_SBXOFFSET_UNIT              1097
#define IDC_SBYOFFSET_UNIT              1098
#define IDC_SBXSCALE_UNIT               1099
#define IDC_SBYSCALE_UNIT               1100
#define IDC_SBANGLE_UNIT                1101
#define IDC_SBXOFFSET_INCR              1111
#define IDC_CBSKYBACK                   1111
#define IDC_SBYOFFSET_INCR              1112
#define IDC_CBSKYLEFT                   1112
#define IDC_SBXSCALE_INCR               1113
#define IDC_SBYSCALE_INCR               1114
#define IDC_SBANGLE_INCR                1115
#define IDC_APPLY                       1118
#define IDC_RESTORE                     1119
#define IDC_COLOR                       1119
#define IDC_CANCEL                      1120
#define IDC_GROUP1                      1128
#define IDC_TEXTURELIST                 1132
#define IDD_TEXTUREDIALOG               1132
#define IDC_TEXTUREIMAGE                1133
#define IDC_APPLYTEXTURE                1134
#define IDC_CUBE_PRIMITIVE              1138
#define IDC_SPHEROID_PRIMITIVE          1139
#define IDC_CYLINDER_PRIMITIVE          1140
#define IDC_STAIRCASE_PRIMITIVE         1141
#define IDC_LIGHT_ENTITY                1142
#define IDC_BUILDALWAYS                 1142
#define IDC_ENTITIES                    1142
#define IDC_PLAYERSTART_ENTITY          1143
#define IDC_FLIPVERTICAL                1143
#define IDC_ACTOR_ENTITY                1144
#define IDC_FLIPHORIZONTAL              1144
#define IDC_ARCH_PRIMITIVE              1145
#define IDC_CONE_PRIMITIVE              1146
#define IDC_STARTANGLE                  1148
#define IDC_ENDANGLE                    1149
#define IDC_STATUSPROGRESS1             1149
#define IDC_STATUSPROGRESS2             1150
#define IDC_FUNNEL                      1152
#define IDC_VISNONE                     1157
#define IDC_VISLEVEL1                   1158
#define IDC_VISLEVEL2                   1159
#define IDC_VISLEVEL3                   1160
#define IDC_VISLEVEL4                   1161
#define IDC_RUNGBSP                     1162
#define IDC_RUNLIGHT                    1163
#define IDC_RunAvenger                  1164
#define IDC_VISLEVEL0                   1165
#define IDC_VIS                         1165
#define IDC_TCUT                        1166
#define IDC_CONEDIT                     1167
#define IDC_TSHEET                      1167
#define IDC_STATIC2                     1168
#define IDC_MILLIRADIO                  1170
#define IDC_BRUSHEMPTY                  1170
#define IDC_CENTIRADIO                  1171
#define IDC_METERRADIO                  1172
#define IDC_RADBOOL                     1173
#define IDC_8RADIO                      1173
#define IDC_EXSAMPBOOL                  1174
#define IDC_RADIO5                      1174
#define IDC_16RADIO                     1174
#define IDC_FASTPBOOL                   1175
#define IDC_RADIO6                      1175
#define IDC_32RADIO                     1175
#define IDC_BRUSHHOLLOW                 1175
#define IDC_FULLVIS                     1176
#define IDC_1RADIO                      1176
#define IDC_VISVERBOSE                  1177
#define IDC_2RADIO                      1177
#define IDC_BSPVERBOSE                  1178
#define IDC_ENTITYCOMBO                 1178
#define IDC_4RADIO                      1178
#define IDC_ENTITYVERBOSE               1179
#define IDC_USEMINLIGHT                 1180
#define IDC_TJUNCT                      1181
#define IDC_XEDIT                       1182
#define IDC_YEDIT                       1183
#define IDC_ZEDIT                       1184
#define IDC_STRUCTLIST                  1185
#define IDC_SIZETEXT                    1188
#define IDC_MODELLIST                   1189
#define IDC_BRUSHLOCK                   1190
#define IDC_DESELECTBRUSHES             1191
#define IDC_SELECTBRUSHES               1192
#define IDC_SELECTBRUSHES2              1193
#define IDC_SELECTBRUSHES3              1194
#define IDC_ADDTOCURRENT                1194
#define IDC_SELECTBRUSHES4              1195
#define IDC_REMOVEFROMCURRENT           1195
#define IDC_VISIBLE                     1196
#define IDC_SUPPRESSHIDDEN              1197
#define IDC_SELECTBRUSHES5              1197
#define IDC_CREATENEWGROUP              1197
#define IDC_REMOVEGROUP                 1198
#define IDC_DESELECT                    1199
#define IDC_ADDKEY                      1200
#define IDC_ANIMATE                     1200
#define IDC_ADDEVENT                    1201
#define IDC_DELETEKEY                   1202
#define IDC_SELECT                      1203
#define IDC_DELETEEVENT                 1204
#define IDC_DELETEMODEL                 1205
#define IDC_MODELCOMBO                  1206
#define IDC_KEYSLIST                    1207
#define IDC_ADDMODEL                    1208
#define IDC_ADDBRUSHES                  1209
#define IDC_REMOVEBRUSHES               1210
#define IDC_EDITMODEL                   1211
#define IDC_EDITKEY                     1212
#define IDC_EDITEVENT                   1213
#define IDC_TEXELRADIO                  1214
#define IDC_METRICRADIO                 1215
#define IDC_GROUPCOMBO                  1216
#define IDC_METRICGRID                  1217
#define IDC_LOCKED                      1218
#define IDC_TEXELGRID                   1219
#define IDC_SPINROTSNAPDEGREES          1220
#define IDC_BRUSHSOLID                  1221
#define IDC_SETMODELORIGIN              1222
#define IDC_BRUSHWINDOW                 1223
#define IDC_CLONEMODEL                  1224
#define IDC_BRUSHWAVY                   1225
#define IDC_LOCKORIGIN                  1226
#define IDC_BRUSHFLOCKING               1226
#define IDC_BRUSHCLIP                   1227
#define IDC_BRUSHHINT                   1228
#define IDC_FACEMIRROR                  1229
#define IDC_BRUSHSHEET                  1229
#define IDC_BRUSHAREA                   1230
#define IDC_FACEFULLBRIGHT              1231
#define IDC_PREFSGRIDBG                 1232
#define IDC_FACEGOURAUD                 1232
#define IDC_FACESKY                     1233
#define IDC_PREFSGRIDMAJOR              1234
#define IDC_PREFSGRID                   1234
#define IDC_FACEFLAT                    1234
#define IDC_BRUSHSUBTRACT               1235
#define IDC_SKYLEFT                     1236
#define IDC_FACELIGHT                   1237
#define IDC_PREFSGRIDMINOR              1238
#define IDC_PREFSSNAPGRID               1238
#define IDC_CBSKYRIGHT                  1239
#define IDC_PATHPREFS                   1239
#define IDC_BRUSHTRANSLUCENT            1240
#define IDC_CBSKYTOP                    1241
#define IDC_CBSKYBOTTOM                 1242
#define IDC_CBSKYFRONT                  1243
#define IDC_BRUSHDETAIL                 1244
#define IDC_EVENTTIME                   1245
#define IDC_EVENTSTRING                 1246
#define IDC_ENTITIESONLY                1247
#define IDC_EDITXOFFSET                 1248
#define IDC_EDITYOFFSET                 1249
#define IDC_EDITXSCALE                  1250
#define IDC_EDITYSCALE                  1251
#define IDC_EDITANGLE                   1252
#define IDC_CBXOFFSET                   1253
#define IDC_CBYOFFSET                   1254
#define IDC_CBXSCALE                    1255
#define IDC_CBYSCALE                    1256
#define IDC_CBANGLE                     1257
#define IDC_EDITXLIGHTSCALE             1258
#define IDC_EDITYLIGHTSCALE             1259
#define IDC_SBXLIGHTSCALE_UNIT          1260
#define IDC_SBYLIGHTSCALE_UNIT          1261
#define IDC_SBXLIGHTSCALE_INCR          1262
#define IDC_SBYLIGHTSCALE_INCR          1263
#define IDC_CBXLIGHTSCALE               1264
#define IDC_CBYLIGHTSCALE               1265
#define IDC_EDITTRANSLUCENCY            1266
#define IDC_LBLTRANSLUCENCYVALUE        1269
#define IDC_LBLHULLSIZE                 1270
#define IDC_EDITTXLSEARCH               1271
#define IDC_EDITPREVIEW                 1272
#define IDC_EDITHEADERS                 1273
#define IDC_EDITOBJECTSDIR              1274
#define IDC_EDITTXLIB                   1275
#define IDC_PATHS                       1276
#define IDC_COMPILEOPTIONS              1277
#define IDC_SAVE                        1278
#define IDC_LIGHTMAPSCALE               1279
#define IDC_DRAWSCALE                   1280
#define IDC_BOOLLIST                    1281
#define IDC_EDITTXL                     1281
#define IDC_CONTENTSLIST                1282
#define IDC_EDITHEADERSDIR              1282
#define IDC_MIPMAPBIAS                  1283
#define IDC_TEXTURELOCK                 1284
#define IDC_AXISX                       1285
#define IDC_REFLECTIVITY                1285
#define IDC_AXISY                       1286
#define IDC_FACETRANSLUCENCY            1286
#define IDC_AXISZ                       1287
#define IDC_EDITSPEED                   1288
#define IDC_EDITSCALE                   1289
#define IDC_TRANSPARENT                 1289
#define IDC_BROWSETXL                   1290
#define ID_BRUSH_PRIMITIVES_CUBE        32771
#define ID_BRUSH_PRIMITIVES_PYRAMID     32772
#define ID_BRUSH_PRIMITIVES_SPHEROID    32773
#define ID_BRUSH_PRIMITIVES_CONE        32774
#define ID_BRUSH_PRIMITIVES_CYLINDER    32775
#define ID_BRUSH_SUBTRACTFROMWORLD      32776
#define ID_TOOLS_CAMERA                 32777
#define ID_AXIS_X                       32781
#define ID_AXIS_Y                       32782
#define ID_AXIS_Z                       32783
#define ID_TOOLS_BRUSH_MOVEROTATEBRUSH  32784
#define ID_TOOLS_BRUSH_SCALEBRUSH       32785
#define ID_TOOLS_BRUSH_RESETBRUSH       32786
#define ID_TOOLS_BRUSH_ATTRIBUTES       32791
#define ID_TOOLS_BRUSH_SHOWBRUSH        32792
#define ID_FILE_EXPORT                  32799
#define ID_TOOLS_USEGRID                32801
#define ID_TOOLS_GRIDSETTINGS           32802
#define ID_VIEW_3DWIREFRAME             32806
#define ID_VIEW_SOLIDRENDER             32807
#define ID_VIEW_TOPVIEW                 32808
#define ID_VIEW_SIDEVIEW                32809
#define ID_VIEW_FRONTVIEW               32810
#define ID_VIEW_TEXTUREVIEW             32811
#define ID_VIEW_4VIEWS                  32812
#define ID_TOOLS_BSPMANAGER             32813
#define ID_TOOLS_BRUSH_SHEARBRUSH       32814
#define ID_ENTITIES_PLACELIGHT          32817
#define ID_ENTITIES_EDITOR              32819
#define ID_TOOLS_ENTITY                 32823
#define ID_ENTITIES_SHOW                32824
#define ID_GROUPS_MAKENEWGROUP          32833
#define ID_BRUSH_GROUPEDITOR            32834
#define ID_VIEW_SHOW_ALLGROUPS          32836
#define ID_VIEW_SHOW_VISIBLEGROUPS      32837
#define ID_VIEW_SHOW_CURRENTGROUP       32838
#define ID_TOOLS_BRUSH_ADJUSTMENTMODE   32849
#define ID_BRUSH_SELECTED_DELETE        32850
#define ID_BRUSH_SELECTED_COPYTOCURRENT 32853
#define ID_BRUSH_PRIMITIVES_STAIRCASE   32856
#define ID_TOOLS_BRUSH_ROTATE90         32857
#define ID_VIEW_TEXTUREBROWSER          32859
#define ID_FILE_MAPSETTINGS             32860
#define ID_GBSPNOWATER                  32861
#define ID_ENTITIES_COPYCURRENT         32862
#define ID_ENTITIES_HIDENONLIGHTS       32865
#define ID_TOOLS_BRUSH_MOVESELECTEDBRUSHES 32867
#define ID_TOOLS_GROUPMOVEMENTMODE      32870
#define ID_BRUSH_REMOVESELECTEDFROMGROUP 32871
#define ID_TOOLS_FACE_ATTRIBUTES        32876
#define ID_TOOLS_FACE_RESETFACE         32881
#define ID_TOOLS_FACE_ADJUSTMENTMODE    32883
#define ID_CONSTRAINHOLLOWS             32885
#define ID_GENERALSELECT                32886
#define ID_VIEW_OLDVIEW                 32890
#define ID_TOOLS_RESET_THING            32890
#define ID_THING_ATTRIBUTES             32891
#define ID_TOOLS_CARVE                  32892
#define IDC_VIEWTOOLBAR_COMBOBOX        32893
#define ID_VIEW_3DVIEWBARS              32903
#define ID_TOOLS_BRUSH_SHOWASSOCIATEDENTITY 32905
#define ID_ENTITY_CENTERINBRUSH         32906
#define ID_CENTERTHING                  32908
#define ID_COMPILE                      32909
#define ID_TOOLS_TEMPLATE               32910
#define ID_MODEL_NEW                    32913
#define ID_NEW_LIB_OBJECT               32914
#define ID_MODEL_DELETE                 32915
#define ID_MODEL_ADDSELECTEDBRUSHES     32916
#define ID_MODEL_REMOVESELECTEDBRUSHES  32917
#define ID_MODEL_SELECTBRUSHES          32918
#define ID_MODEL_DESELECTMODELBRUSHES   32919
#define ID_MODEL_SELECTMODEL            32920
#define ID_ENTITYVISIBILITY             32922
#define ID_VIEW_NEW                     32923
#define ID_BRUSHINFORMATION             32924
#define IDC_PLACE_OBJECT_BUTTON         32925
#define IDS_CANT_OPEN_FILE              32925
#define IDC_OBJECT_SELECT_COMBO         32926
#define IDC_ENTITY_COMBO                32927
#define IDM_MODEBAR                     32928
#define IDM_TABBAR                      32929
#define IDM_GROUPBAR                    32933
#define ID_GROUPBAR_SEP                 32934
#define ID_GROUPBAR_COM                 32935
#define ID_ADDTOCURRENT                 32937
#define ID_REMOVEFROMCURRENT            32938
#define ID_DESELECTALL                  32941
#define ID_SELECTALL                    32942
#define IDM_REBUILD_BSP                 32943
#define ID_VIEWLEAKFINDER               32944
#define IDM_PREFERENCES                 32945
#define ID_VIEW_SHOW_CLIP               32947
#define ID_VIEW_SHOW_HINT               32949
#define ID_VIEW_SHOW_DETAIL             32950
#define ID_TOOLS_SCALEWORLD             32951
#define ID_TOOLS_BRUSH_MAKENEWEST       32952
#define ID_TOOLS_SETTEXTURESCALE        32953
#define ID_EDIT_DELETE                  32954
#define ID_BRUSH_PRIMITIVES_ARCH        32955
#define ID_TOOLS_NEXTBRUSH              32956
#define ID_TOOLS_PREVBRUSH              32957
#define ID_TOOLS_ADDTOLEVEL             32958
#define ID_TOOLS_TOGGLEADJUSTMODE       32959
#define ID_VIEW_ZOOMIN                  32960
#define ID_VIEW_ZOOMOUT                 32961
#define ID_FILE_IMPORT                  32962
#define ID_HELP_HOWDOI                  32965
#define IDM_LEVELOPTIONS                32966
#define IDS_CANTLOADTXL                 32967
#define IDS_ENTITY_WARNING              32968

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        234
#define _APS_NEXT_COMMAND_VALUE         32967
#define _APS_NEXT_CONTROL_VALUE         1291
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
