//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TPack.rc
//
#define IDS_CLASSNAME                   1
#define IDS_PROGRAMNAME                 2
#define IDS_UNIQUEMESSAGE               3
#define IDS_DEFAULTPOSE                 4
#define IDS_BLENDEDMOTION               5
#define IDR_MENU1                       101
#define IDD_DRIVERDIALOG                102
#define IDD_ACTOR                       103
#define IDD_TEXTUREPACKER               103
#define IDD_BLENDER                     105
#define IDI_FRAME                       106
#define IDI_MAINICON                    107
#define IDI_ZOOM                        108
#define IDS_CANTCREATEENGINE            109
#define IDS_CANTCREATECAMERA            110
#define IDI_PAN                         111
#define IDS_CANTCREATEWORLD             111
#define IDS_CANTLOADDRIVER              112
#define IDI_ROTATE                      113
#define IDS_CANTINITENGINE              113
#define IDS_CANTLOADACTOR               114
#define IDR_ACCELERATOR1                115
#define IDD_ABOUT                       116
#define IDS_BEGINFRAMEFAIL              116
#define IDS_RENDERFAIL                  117
#define IDS_INIFILENAME                 118
#define IDS_ENDFRAMEFAIL                119
#define IDS_HELPFILENAME                120
#define IDS_PROGRAMBASENAME             121
#define IDS_ACTFILEFILTER               122
#define IDS_ACTFILEEXT                  123
#define IDS_ACTFILEFILTERDESC           124
#define IDS_UNNAMED                     125
#define IDB_TPACK                       126
#define IDD_NEWDIALOG                   127
#define IDI_BLEND                       128
#define IDC_DRIVERLIST                  1000
#define IDC_MOTIONLIST                  1000
#define IDC_PAN                         1001
#define IDC_ROTATE                      1002
#define IDC_ZOOM                        1003
#define IDI_PLAY                        1004
#define IDI_PAUSE                       1005
#define IDI_RRSTART                     1006
#define IDI_RRFRAME                     1007
#define IDI_STOP                        1008
#define IDI_FFFRAME                     1009
#define IDI_FFEND                       1010
#define IDC_FRONT                       1011
#define IDC_MOTIONCOMBO                 1012
#define IDC_EDITSCALE                   1013
#define IDC_BACK                        1014
#define IDC_SLIDERTIME                  1015
#define IDC_EDITSPEED                   1016
#define IDC_LEFT                        1017
#define IDC_STATICSCALE                 1018
#define IDC_STATICMOTION                1019
#define IDC_RENDERWIN                   1020
#define IDC_STATICSPEED                 1021
#define IDC_RIGHT                       1022
#define IDC_SPINSCALE                   1023
#define IDC_SPINSPEED                   1024
#define IDC_EDITFRAMETIME               1025
#define IDC_SPINFRAMETIME               1026
#define IDC_STATICFRAME                 1027
#define IDC_TOP                         1028
#define IDC_BOTTOM                      1029
#define IDC_STATICEND                   1030
#define IDC_STATICSTART                 1031
#define IDS_STATICSTART                 1031
#define IDC_STATICCURRENTTIME           1032
#define IDC_LOOPED                      1033
#define IDC_CENTER                      1034
#define IDC_EDITDIR                     1035
#define IDC_STATICMOTION2               1035
#define IDC_TAB1                        1036
#define IDC_LIST1                       1037
#define IDC_MOTIONSLIST                 1037
#define IDC_TEXTURELIST                 1037
#define IDC_LIST2                       1038
#define IDC_BLENDLIST                   1038
#define IDC_BUTTON1                     1039
#define IDC_BLEND                       1039
#define IDC_ADD                         1039
#define IDC_BUTTON2                     1040
#define IDC_MOVEUP                      1040
#define IDC_BUTTON3                     1041
#define IDC_REMOVE                      1041
#define IDC_BUTTON4                     1042
#define IDC_MOVEDOWN                    1042
#define IDC_EDITTIMEOFFSET              1043
#define IDC_SLIDERTIMEOFFSET            1044
#define IDC_EDITTIMESCALE               1045
#define IDC_EDITSTARTTIME               1046
#define IDC_SLIDERSTARTTIME             1047
#define IDC_EDITENDTIME                 1048
#define IDC_SLIDERENDTIME               1049
#define IDC_EDITSTARTBLEND              1050
#define IDC_EDITENDBLEND                1051
#define IDC_SPINSTARTBLEND              1052
#define IDC_SPINENDBLEND                1053
#define IDC_CHECKSMOOTHBLEND            1054
#define IDC_BLENDPATH                   1055
#define IDC_STATICMOTIONEND             1056
#define IDC_TESTOUT                     1057
#define IDC_STATICBLEND                 1060
#define IDC_STATICSUBMOTION             1061
#define IDC_TEXTURESIZE                 1062
#define IDC_PREVIEW                     1063
#define ID_FILE_EXIT                    40001
#define ID_FILE_OPEN                    40002
#define ID_MOTION_SELECT                40003
#define ID_START                        40004
#define ID_OPTIONS_FRONT                40005
#define ID_HELP_CONTENTS                40006
#define ID_HELP_ABOUT                   40007
#define ID_OPTIONS_FRAMERATE            40008
#define IDS_CANTADDWORLD                40009
#define IDS_CANTSTARTTIMER              40010
#define IDC_NOTHING                     40011
#define ID_FILE_SAVE                    40012
#define ID_FILE_SAVEAS                  40013
#define ID_OPTIONS_EXTRACTALL           40014
#define ID_OPTIONS_EXTRACTSELECTED      40015
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         40016
#define _APS_NEXT_CONTROL_VALUE         1064
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
